---
name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
          cache: npm

      # Can be removed once moved to Node.js 24+ LTS
      - name: upgrade
        run: npm install -g npm@latest

      - name: install
        run: npm ci

      - name: build
        run: npm run build
