---
name: publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      # Publish to npmjs using a newer version of npm, as
      # Node.js v22 (required by the Strapi plugin API) ships
      # with npm 10 and npm 11 is required to use OIDC
      # Can be removed once moved to Node.js 24+ LTS
      - name: upgrade
        run: npm install -g npm@latest

      - name: install
        run: npm ci

      - name: build
        run: npm run build

      - name: publish
        run: npm publish --access public --provenance
